"""Official Python SDK for the Sales Tax Calculator API.

Docs: https://salestaxcalculatorapi.com/docs
"""

from __future__ import annotations

from ._config import (
    MAX_BATCH_SIZE,
    MAX_LINES_PER_ADJUSTMENT,
    MAX_LINES_PER_CALCULATION,
    MAX_REGISTRATIONS,
    ClientOptions,
    RetryPolicy,
)
from ._version import __version__
from .client import AsyncSalesTaxClient, SalesTaxClient
from .errors import (
    ApiError,
    AuthenticationError,
    ConflictError,
    ConnectionError,
    NotFoundError,
    PermissionError,
    RateLimitError,
    SalesTaxError,
    ServerError,
    TimeoutError,
    ValidationError,
)
from .models import (
    Address,
    Adjustment,
    AdjustmentLine,
    AdjustmentPage,
    AuditExpansion,
    BillingEvent,
    Calculation,
    CalculationBatch,
    CalculationBatchCreate,
    CalculationCreate,
    CalculationLine,
    CalculationLineCreate,
    Coverage,
    CoverageQuery,
    Customer,
    CustomerType,
    EvidenceResult,
    Jurisdiction,
    ListAdjustmentsParams,
    LocationEvidence,
    Outcome,
    Seller,
    SellerChannelRole,
    SellerRegistration,
    TaxBehavior,
    TaxComponent,
    TaxIdInput,
    Transaction,
    TransactionCreate,
    TransactionType,
)

__all__ = [
    "MAX_BATCH_SIZE",
    "MAX_LINES_PER_ADJUSTMENT",
    "MAX_LINES_PER_CALCULATION",
    "MAX_REGISTRATIONS",
    "Address",
    "Adjustment",
    "AdjustmentLine",
    "AdjustmentPage",
    "ApiError",
    "AsyncSalesTaxClient",
    "AuditExpansion",
    "AuthenticationError",
    "BillingEvent",
    "Calculation",
    "CalculationBatch",
    "CalculationBatchCreate",
    "CalculationCreate",
    "CalculationLine",
    "CalculationLineCreate",
    "ClientOptions",
    "ConflictError",
    "ConnectionError",
    "Coverage",
    "CoverageQuery",
    "Customer",
    "CustomerType",
    "EvidenceResult",
    "Jurisdiction",
    "ListAdjustmentsParams",
    "LocationEvidence",
    "NotFoundError",
    "Outcome",
    "PermissionError",
    "RateLimitError",
    "RetryPolicy",
    "SalesTaxClient",
    "SalesTaxError",
    "Seller",
    "SellerChannelRole",
    "SellerRegistration",
    "ServerError",
    "TaxBehavior",
    "TaxComponent",
    "TaxIdInput",
    "TimeoutError",
    "Transaction",
    "TransactionCreate",
    "TransactionType",
    "ValidationError",
    "__version__",
]
